### ISSUE TITLE
Fazer o deploy

### ISSUE THREAD

**Issue by alnnu** [alnnu/portfolio#6]
### TODO

- [] Fazer docker do deploy
- [] pesquisar como fazer o nginx proxy
- [] fazer o nginx proxy
